//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : SU_Ciudad.java
//  @ Date : 28/03/2009
//  @ Author : Guillermo Pizarro
//  @ Version : v1.0.0
//
//

package websae.msu.dominio;

import java.math.BigDecimal;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import mad.eventos.Datos;
import mad.objetos.Registro;
import mad.objetos.Table;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import websae.informacion.Estado;
import websae.mac.dominio.AC_Usuario;


public class SU_Ciudad {

	public List< SU_Empresa > ref_empresa;
	public List< AC_Usuario > ref_usuario;

    public SU_Pais ref_pais;

    // <editor-fold defaultstate="collapsed" desc="Atributos">
    private BigDecimal ci_id_ciudad;
    private String ci_nombre;
    private String ci_distrito;
    private String ci_estado;
    // </editor-fold>

    public SU_Ciudad() {
        this.ref_pais = new SU_Pais();
    }

    public BigDecimal getCi_id_ciudad() {
        return ci_id_ciudad;
    }

    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public String getCi_distrito() {
        return ci_distrito;
    }

    public void setCi_distrito(String ci_distrito) {
        this.ci_distrito = ci_distrito;
    }

    public String getCi_estado() {
        return ci_estado;
    }

    public void setCi_estado(String ci_estado) {
        this.ci_estado = ci_estado;
    }

    public void setCi_id_ciudad(BigDecimal ci_id_ciudad) {
        this.ci_id_ciudad = ci_id_ciudad;
    }

    public String getCi_nombre() {
        return ci_nombre;
    }

    public void setCi_nombre(String ci_nombre) {
        this.ci_nombre = ci_nombre;
    }

    public List<SU_Empresa> getRef_empresa() {
        return ref_empresa;
    }

    public void setRef_empresa(List<SU_Empresa> ref_empresa) {
        this.ref_empresa = ref_empresa;
    }

    public SU_Pais getRef_pais() {
        return ref_pais;
    }

    public void setRef_pais(SU_Pais ref_pais) {
        this.ref_pais = ref_pais;
    }

    public List<AC_Usuario> getRef_usuario() {
        return ref_usuario;
    }

    public void setRef_usuario(List<AC_Usuario> ref_usuario) {
        this.ref_usuario = ref_usuario;
    }
    // </editor-fold>

	public void cr_SU_Ciudad(Table objeto) {
        this.ci_id_ciudad = new BigDecimal( (Long) objeto.get("ci_id_ciudad") );
        this.ci_nombre = (String) objeto.get("ci_nombre");
        this.ci_distrito = (String) objeto.get("ci_distrito");
        this.ci_estado = (String) objeto.get("ci_estado");
	}

	public void cr_SU_Ciudad(Table objeto, String ref_pais) {
        this.ci_id_ciudad = new BigDecimal( (Long) objeto.get("ci_id_ciudad") );
        this.ci_nombre = (String) objeto.get("ci_nombre");
        this.ci_distrito = (String) objeto.get("ci_distrito");
        this.ci_estado = (String) objeto.get("ci_estado");

        this.ref_pais.setPa_id_pais( ref_pais );
	}

	public void fin_SU_Ciudad() {
	}

    public static SU_Ciudad buscar_ciudad(BigDecimal id_ciudad) {
        SU_Ciudad ciudad = new SU_Ciudad();

        Datos datos = new Datos("WebSAE");
        Registro registros = datos.consulta( "SELECT * FROM su_ciudad WHERE ci_id_ciudad = " + id_ciudad +";" );
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            ciudad.cr_SU_Ciudad( objeto, (String) objeto.get("ref_pais") );
        }
        return ciudad;
    }

    public static List< SU_Ciudad > mostrar_ciudades(String id_pais) {
        List< SU_Ciudad > ciudades = new LinkedList<SU_Ciudad>();

        Datos datos = new Datos("WebSAE");
        String sql = "SELECT ci.ci_id_ciudad, ci.ci_nombre, ci.ci_distrito, ci.ci_estado " +
                     "FROM SU_Pais pa, SU_Ciudad ci " +
                     "WHERE pa.pa_id_pais = '" + id_pais + "' AND pa.pa_id_pais = ci.ref_pais AND ci.ci_estado = '" + Estado.VIGENTE + "' ORDER BY ci.ci_nombre;";
        Registro registros = datos.consulta( sql );
        for (int i=0; i<registros.size(); i++) {
            SU_Ciudad ciudad = new SU_Ciudad();
            ciudad.cr_SU_Ciudad( (Table) registros.get(i) );
            ciudades.add(ciudad);
        }
        return ciudades;
    }

    public static JSONObject toJSON(List< SU_Ciudad > ciudades) {
        JSONObject json = new JSONObject();
        try {
            JSONArray jsonItems = new JSONArray();
            for (Iterator<SU_Ciudad> it = ciudades.iterator(); it.hasNext();) {
                SU_Ciudad ciudad = it.next();
                jsonItems.put( toJSONObject( ciudad ) );
            }
            json.put("identifier", "id_ciudad");
            json.put("label", "nombre");
            json.put("items", jsonItems);
        } catch (JSONException ex) {
            Logger.getLogger(SU_Ciudad.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }

    public static JSONObject toJSONObject(SU_Ciudad ciudad) {
        JSONObject json = new JSONObject();
        try {
            json.put("id_ciudad", ciudad.getCi_id_ciudad() );
            json.put("nombre", ciudad.getCi_nombre() );
            json.put("distrito", ciudad.getCi_distrito() );
            json.put("estado", ciudad.getCi_estado() );

            if (ciudad.ref_pais != null && ciudad.ref_pais.getPa_id_pais() != null)
                json.put("pais", SU_Pais.toJSONObject( SU_Pais.buscar_pais(ciudad.ref_pais.getPa_id_pais()) ) );
        } catch (Exception ex) {
            Logger.getLogger(SU_Ciudad.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }
}
