//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : SU_Empresa.java
//  @ Date : 28/03/2009
//  @ Author : Guillermo Pizarro
//  @ Version : v1.0.0
//
//

package websae.msu.dominio;

import java.math.BigDecimal;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import mad.eventos.Datos;
import mad.objetos.Registro;
import mad.objetos.Table;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import websae.informacion.Estado;

public class SU_Empresa {

    // <editor-fold defaultstate="collapsed" desc="Objetos Maestros">
	public SU_Tipo_Empresa ref_tipo_empresa;
	public SU_Ciudad ref_ciudad;
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Objetos Dependientes">
	public List< SU_Empresa_Usuario > ref_empresa_usuario;
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Atributos">
    private BigDecimal em_id_empresa;
    private String em_nombre;
    private String em_direccion;
    private String em_telefono;
    private String em_codigo_postal;
    private String em_fax;
    private String em_logo;
    private String em_web;
    private String em_siglas;
    private String em_estado;
    // </editor-fold>

    public SU_Empresa() {
        this.ref_tipo_empresa = new SU_Tipo_Empresa();
    }
    
    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public String getEm_codigo_postal() {
        return em_codigo_postal;
    }

    public void setEm_codigo_postal(String em_codigo_postal) {
        this.em_codigo_postal = em_codigo_postal;
    }

    public String getEm_direccion() {
        return em_direccion;
    }

    public void setEm_direccion(String em_direccion) {
        this.em_direccion = em_direccion;
    }

    public String getEm_estado() {
        return em_estado;
    }

    public void setEm_estado(String em_estado) {
        this.em_estado = em_estado;
    }

    public String getEm_fax() {
        return em_fax;
    }

    public void setEm_fax(String em_fax) {
        this.em_fax = em_fax;
    }

    public BigDecimal getEm_id_empresa() {
        return em_id_empresa;
    }

    public void setEm_id_empresa(BigDecimal em_id_empresa) {
        this.em_id_empresa = em_id_empresa;
    }

    public String getEm_logo() {
        return em_logo;
    }

    public void setEm_logo(String em_logo) {
        this.em_logo = em_logo;
    }

    public String getEm_nombre() {
        return em_nombre;
    }

    public void setEm_nombre(String em_nombre) {
        this.em_nombre = em_nombre;
    }

    public String getEm_siglas() {
        return em_siglas;
    }

    public void setEm_siglas(String em_siglas) {
        this.em_siglas = em_siglas;
    }

    public String getEm_telefono() {
        return em_telefono;
    }

    public void setEm_telefono(String em_telefono) {
        this.em_telefono = em_telefono;
    }

    public String getEm_web() {
        return em_web;
    }

    public void setEm_web(String em_web) {
        this.em_web = em_web;
    }

    public SU_Ciudad getRef_ciudad() {
        return ref_ciudad;
    }

    public void setRef_ciudad(SU_Ciudad ref_ciudad) {
        this.ref_ciudad = ref_ciudad;
    }

    public List<SU_Empresa_Usuario> getRef_empresa_usuario() {
        return ref_empresa_usuario;
    }

    public void setRef_empresa_usuario(List<SU_Empresa_Usuario> ref_empresa_usuario) {
        this.ref_empresa_usuario = ref_empresa_usuario;
    }
    
    public SU_Tipo_Empresa getRef_tipo_empresa() {
        return ref_tipo_empresa;
    }

    public void setRef_tipo_empresa(SU_Tipo_Empresa ref_tipo_empresa) {
        this.ref_tipo_empresa = ref_tipo_empresa;
    }
    
    // </editor-fold>
    
    public void cr_SU_Empresa() {
        this.ref_ciudad = new SU_Ciudad();
        this.ref_tipo_empresa = new SU_Tipo_Empresa();
    }

	public void cr_SU_Empresa(String em_id_empresa, String em_nombre, String em_direccion, String em_telefono, String em_codigo_postal, String em_fax, String em_logo, String em_web, String em_siglas, String em_estado) {
        this.em_id_empresa = new BigDecimal(em_id_empresa);
        this.em_nombre = em_nombre;
        this.em_direccion = em_direccion;
        this.em_telefono = em_telefono;
        this.em_codigo_postal = em_codigo_postal;
        this.em_fax = em_fax;
        this.em_logo = em_logo;
        this.em_web = em_web;
        this.em_siglas = em_siglas;
        this.em_estado = em_estado;
	}
	
	public void fin_SU_Empresa() {
        
	}
    
    public static SU_Empresa buscar_empresa(BigDecimal id_empresa) {
        SU_Empresa empresa = new SU_Empresa();
        
        Datos datos = new Datos("WebSAE");
        Registro registros = datos.consulta("SELECT * FROM su_empresa WHERE em_id_empresa=" + id_empresa + ";");
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            empresa.cr_SU_Empresa(objeto.get("em_id_empresa").toString(), (String)objeto.get("em_nombre"), (String)objeto.get("em_direccion"), (String)objeto.get("em_telefono"), (String)objeto.get("em_codigo_postal"), (String)objeto.get("em_fax"), (String)objeto.get("em_logo"), (String)objeto.get("em_web"), (String)objeto.get("em_siglas"), (String)objeto.get("em_estado"));
        }
        return empresa;
    }
    
    public static List< SU_Empresa > empresas() {
        List< SU_Empresa > empresas = new LinkedList< SU_Empresa >();
        
        Datos datos = new Datos("WebSAE");
        Registro registros = datos.consulta("SELECT * FROM su_empresa ORDER BY em_nombre;");
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            SU_Empresa empresa = new SU_Empresa();
            empresa.cr_SU_Empresa(objeto.get("em_id_empresa").toString(), (String)objeto.get("em_nombre"), (String)objeto.get("em_direccion"), (String)objeto.get("em_telefono"), (String)objeto.get("em_codigo_postal"), (String)objeto.get("em_fax"), (String)objeto.get("em_logo"), (String)objeto.get("em_web"), (String)objeto.get("em_siglas"), (String)objeto.get("em_estado"));
            empresas.add( empresa );
        }
        return empresas;
    }
    
    public static List< SU_Empresa > mostrar_empresas() {
        List< SU_Empresa > empresas = new LinkedList< SU_Empresa >();

        Datos datos = new Datos("WebSAE");
        Registro registros = datos.consulta("SELECT * FROM su_empresa WHERE em_estado = '"+Estado.VIGENTE+"';");
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            SU_Empresa empresa = new SU_Empresa();
            empresa.cr_SU_Empresa(objeto.get("em_id_empresa").toString(), (String)objeto.get("em_nombre"), (String)objeto.get("em_direccion"), (String)objeto.get("em_telefono"), (String)objeto.get("em_codigo_postal"), (String)objeto.get("em_fax"), (String)objeto.get("em_logo"), (String)objeto.get("em_web"), (String)objeto.get("em_siglas"), (String)objeto.get("em_estado"));
            empresas.add( empresa );
        }
        return empresas;
    }
    
    public static List< SU_Empresa > mostrar_empresas_por_tipo_empresa(String id_tipo_empresa) {
        List< SU_Empresa > empresas = new LinkedList< SU_Empresa >();

        Datos datos = new Datos("WebSAE");
        Registro registros = datos.consulta("{call su_mostrar_empresas_por_tipo_empresa("+id_tipo_empresa+")}");
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            SU_Empresa empresa = new SU_Empresa();
            empresa.cr_SU_Empresa(objeto.get("em_id_empresa").toString(), (String)objeto.get("em_nombre"), (String)objeto.get("em_direccion"), (String)objeto.get("em_telefono"), (String)objeto.get("em_codigo_postal"), (String)objeto.get("em_fax"), (String)objeto.get("em_logo"), (String)objeto.get("em_web"), (String)objeto.get("em_siglas"), (String)objeto.get("em_estado"));
            empresas.add( empresa );
        }
        return empresas;
    }

    public static SU_Empresa buscar_empresa(String id_empresa) {
        SU_Empresa empresa = new SU_Empresa();

        Datos datos = new Datos("WebSAE");
        String sql = "SELECT * FROM SU_Empresa WHERE em_id_empresa = " + id_empresa + ";";
        Registro registros = datos.consulta( sql );
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            empresa.cr_SU_Empresa();
            empresa.cr_SU_Empresa(objeto.get("em_id_empresa").toString(), (String)objeto.get("em_nombre"), (String)objeto.get("em_direccion"), (String)objeto.get("em_telefono"), (String)objeto.get("em_codigo_postal"), (String)objeto.get("em_fax"), (String)objeto.get("em_logo"), (String)objeto.get("em_web"), (String)objeto.get("em_siglas"), (String)objeto.get("em_estado"));
            empresa.ref_ciudad.setCi_id_ciudad( new BigDecimal( (Long) objeto.get("ref_ciudad") ) );
            empresa.ref_tipo_empresa.setTe_id_tipo_empresa( new BigDecimal( (Long) objeto.get("ref_tipo_empresa") ) );
        }
        return empresa;
    }
    
    public static JSONObject toJSON(List< SU_Empresa > empresas) {
        JSONObject json = new JSONObject();
        try {
            JSONArray jsonItems = new JSONArray();
            for (Iterator< SU_Empresa > it = empresas.iterator(); it.hasNext();) {
                jsonItems.put( toJSONObject( it.next() ) );
            }
            json.put("identifier", "id_empresa");
            json.put("label", "nombre");
            json.put("items", jsonItems);
        } catch (JSONException ex) {
            Logger.getLogger(SU_Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }
    
    public static JSONObject toJSONObject(SU_Empresa empresa) {
        JSONObject json = new JSONObject();
        try {
            json.put("id_empresa", empresa.getEm_id_empresa() );
            json.put("nombre", empresa.getEm_nombre() );
            json.put("direccion", empresa.getEm_direccion() );
            json.put("telefono", empresa.getEm_telefono() );
            json.put("codigo_postal", empresa.getEm_codigo_postal() );
            json.put("fax", empresa.getEm_fax() );
            json.put("logo", empresa.getEm_logo() );
            json.put("web", empresa.getEm_web() );
            json.put("siglas", empresa.getEm_siglas() );
            json.put("estado", empresa.getEm_estado() );
            
            if (empresa.ref_ciudad != null && empresa.ref_ciudad.getCi_id_ciudad() != null)
                json.put("ciudad", SU_Ciudad.toJSONObject( SU_Ciudad.buscar_ciudad(empresa.ref_ciudad.getCi_id_ciudad()) ) );
            if (empresa.ref_tipo_empresa != null && empresa.ref_tipo_empresa.getTe_id_tipo_empresa() != null)
                json.put("tipo_empresa", SU_Tipo_Empresa.toJSONObject( SU_Tipo_Empresa.buscar_tipo_empresa(empresa.ref_tipo_empresa.getTe_id_tipo_empresa()) ) );
        } catch (Exception ex) {
            Logger.getLogger(SU_Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }
}
