//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : SU_Tipo_Empresa.java
//  @ Date : 28/03/2009
//  @ Author : Guillermo Pizarro
//  @ Version : v1.0.0
//
//

package websae.msu.dominio;

import java.math.BigDecimal;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import mad.eventos.Datos;
import mad.objetos.Registro;
import mad.objetos.Table;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import websae.msu.informacion.SU_Tipo_Empresa_Cargo;

public class SU_Tipo_Empresa {

    // <editor-fold defaultstate="collapsed" desc="Objetos Dependientes">
    public List< SU_Tipo_Empresa_Cargo > ref_tipo_empresa_cargo;
    public List< SU_Empresa > ref_empresa;
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Atributos">
    private BigDecimal te_id_tipo_empresa;
    private String te_nombre;
    private String te_descripcion;
    private String te_estado;
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public String getTe_descripcion() {
        return te_descripcion;
    }

    public void setTe_descripcion(String te_descripcion) {
        this.te_descripcion = te_descripcion;
    }

    public String getTe_estado() {
        return te_estado;
    }

    public void setTe_estado(String te_estado) {
        this.te_estado = te_estado;
    }

    public BigDecimal getTe_id_tipo_empresa() {
        return te_id_tipo_empresa;
    }

    public void setTe_id_tipo_empresa(BigDecimal te_id_tipo_empresa) {
        this.te_id_tipo_empresa = te_id_tipo_empresa;
    }

    public String getTe_nombre() {
        return te_nombre;
    }

    public void setTe_nombre(String te_nombre) {
        this.te_nombre = te_nombre;
    }
    // </editor-fold>
    
	public void cr_SU_Tipo_Empresa(String te_id_tipo_empresa, String te_nombre, String te_descripcion, String te_estado) {
        this.te_id_tipo_empresa = new BigDecimal(te_id_tipo_empresa);
        this.te_nombre = te_nombre;
        this.te_descripcion = te_descripcion;
        this.te_estado = te_estado;
	}
	
	public void fin_SU_Tipo_Empresa() {
        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(SU_Tipo_Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }
	}

    public static SU_Tipo_Empresa buscar_tipo_empresa(BigDecimal te_id_tipo_empresa) {
        SU_Tipo_Empresa tipo_empresa = new SU_Tipo_Empresa();
        
        Datos datos = new Datos("WebSAE");
        Registro registros = datos.consulta("SELECT * FROM su_tipo_empresa WHERE te_id_tipo_empresa = "+te_id_tipo_empresa+";");
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            tipo_empresa.cr_SU_Tipo_Empresa( objeto.get("te_id_tipo_empresa").toString(), (String)objeto.get("te_nombre"), (String)objeto.get("te_descripcion"), (String)objeto.get("te_estado"));
        }
        return tipo_empresa;
    }
    
    public static List< SU_Tipo_Empresa > tipos_empresas() {
        List< SU_Tipo_Empresa > tipos_empresas = new LinkedList< SU_Tipo_Empresa >();

        Datos datos = new Datos("WebSAE");
        Registro registros = datos.consulta("SELECT * FROM su_tipo_empresa ORDER BY te_nombre;");
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            SU_Tipo_Empresa cargo = new SU_Tipo_Empresa();
            cargo.cr_SU_Tipo_Empresa( objeto.get("te_id_tipo_empresa").toString(), (String)objeto.get("te_nombre"), (String)objeto.get("te_descripcion"), (String)objeto.get("te_estado"));
            tipos_empresas.add(cargo);
        }
        return tipos_empresas;
    }
    
    public static List< SU_Tipo_Empresa > mostrar_tipos_empresas_por_cargo(String id_cargo ) {
        List< SU_Tipo_Empresa > tipos_empresas = new LinkedList< SU_Tipo_Empresa >();

        Datos datos = new Datos("WebSAE");
        String sql = "SELECT te.te_id_tipo_empresa, te.te_nombre, te.te_descripcion, te.te_estado " +
                     "FROM su_tipo_empresa_Cargo tec, SU_Tipo_Empresa te " +
                     "WHERE tec.ref_cargo = "+id_cargo+" AND tec.ref_tipo_empresa = te.te_id_tipo_empresa AND tec.te_estado = 'V';";
        Registro registros = datos.consulta( sql );
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            SU_Tipo_Empresa cargo = new SU_Tipo_Empresa();
            cargo.cr_SU_Tipo_Empresa( objeto.get("te_id_tipo_empresa").toString(), (String)objeto.get("te_nombre"), (String)objeto.get("te_descripcion"), (String)objeto.get("te_estado"));
            tipos_empresas.add(cargo);
        }
        return tipos_empresas;
    }
    
    public static List< SU_Tipo_Empresa > mostrar_tipos_empresas() {
        List< SU_Tipo_Empresa > tipos_empresas = new LinkedList< SU_Tipo_Empresa >();

        Datos datos = new Datos("WebSAE");
        Registro registros = datos.consulta("{call su_mostrar_tipos_empresas( )}");
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            SU_Tipo_Empresa cargo = new SU_Tipo_Empresa();
            cargo.cr_SU_Tipo_Empresa( objeto.get("te_id_tipo_empresa").toString(), (String)objeto.get("te_nombre"), (String)objeto.get("te_descripcion"), (String)objeto.get("te_estado"));
            tipos_empresas.add(cargo);
        }
        return tipos_empresas;
    }

    public static JSONObject toJSON(List< SU_Tipo_Empresa > tipo_empresas) {
        JSONObject json = new JSONObject();
        try {
            JSONArray jsonItems = new JSONArray();
            for (Iterator<SU_Tipo_Empresa> it = tipo_empresas.iterator(); it.hasNext();) {
                SU_Tipo_Empresa tipos_empresas = it.next();
                jsonItems.put( toJSONObject( tipos_empresas ) );
            }
            json.put("identifier", "id_tipo_empresa");
            json.put("label", "nombre");
            json.put("items", jsonItems);
        } catch (JSONException ex) {
            Logger.getLogger(SU_Cargo.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }

    public static JSONObject toJSONObject(SU_Tipo_Empresa tipo_empresa) {
        JSONObject json = new JSONObject();
        try {
            json.put("id_tipo_empresa", tipo_empresa.getTe_id_tipo_empresa() );
            json.put("nombre", tipo_empresa.getTe_nombre() );
            json.put("descripcion", tipo_empresa.getTe_descripcion() );
            json.put("estado", tipo_empresa.getTe_estado() );
        } catch (Exception ex) {
            Logger.getLogger(SU_Cargo.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }
}
