/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AD_Gui.java
 *
 * Created on 24/02/2009, 02:36:27 AM
 */

package mad.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import mad.mad.Conexion;
import mad.mad.Configuracion;
import mad.bd.ConexionHSQLDB;

/**
 *
 * @author User
 */
public class AD_Gui extends javax.swing.JFrame {

    public ConexionHSQLDB conexion;
    public Integer id_conexion = null;
    
    /** Creates new form AD_Gui */
    public AD_Gui() {
        initComponents();

        this.conexion = new ConexionHSQLDB();
        Configuracion config = conexion.obtener_configuracion();
        this.host.setText(config.getHost());
        this.puerto.setText(""+config.getPuerto()+"");

        cargar_conexiones();
    }

    public void cargar_conexiones() {
        LinkedList<Conexion> lista = conexion.obtener_conexiones();
        String[] conexiones = new String[lista.size()+1];
        conexiones[0] = "--- Seleccione una conexión ---";
        for (int i=0; i<lista.size(); i++) {
            Conexion conex = (Conexion) lista.get(i);
            conexiones[i+1] = conex.getModulo();
        }
        this.conexion_jComboBox.setModel(new javax.swing.DefaultComboBoxModel( conexiones ));
        this.conexion_jComboBox.addActionListener( new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                LinkedList<Conexion> lista_conexiones = conexion.obtener_conexiones();
                String modulo_ = (String) ((JComboBox)e.getSource( )).getSelectedItem();
                
                for (int i=0; i<lista_conexiones.size(); i++) {
                    Conexion objeto = (Conexion) lista_conexiones.get(i);
                    
                    if (objeto.getModulo().compareTo(modulo_) == 0) {
                        id_conexion = objeto.getId_conexion();
                        modulo.setText(objeto.getModulo());
                        base_datos.setText(objeto.getBase_datos());
                        usuario_bd.setText(objeto.getUsuario());
                        clave_bd.setText(objeto.getClave());
                        break;
                    } else {
                        id_conexion = null;
                        modulo.setText("");
                        base_datos.setText("");
                        usuario_bd.setText("");
                        clave_bd.setText("");
                    }
                }
            }
        } );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adaTabbedPane = new javax.swing.JTabbedPane();
        configuracion_jLayeredPane = new javax.swing.JLayeredPane();
        puerto = new javax.swing.JTextField();
        host = new javax.swing.JTextField();
        host_jLabel = new javax.swing.JLabel();
        puerto_jLabel = new javax.swing.JLabel();
        actualizar_configuracion_jButton = new javax.swing.JButton();
        conexion_jLayeredPane = new javax.swing.JLayeredPane();
        modulo = new javax.swing.JTextField();
        conexion_jLabel = new javax.swing.JLabel();
        base_datos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        clave_bd = new javax.swing.JTextField();
        usuario_bd = new javax.swing.JTextField();
        conexion_jComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ingresar_conexion_jButton = new javax.swing.JButton();
        actualizar_conexion_jButton = new javax.swing.JButton();
        eliminar_conexion_jButton = new javax.swing.JButton();
        actualizar_conexion_jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAD");
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        adaTabbedPane.setBackground(new java.awt.Color(204, 204, 255));

        puerto.setBounds(190, 110, 120, 20);
        configuracion_jLayeredPane.add(puerto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        host.setBounds(190, 80, 120, 20);
        configuracion_jLayeredPane.add(host, javax.swing.JLayeredPane.DEFAULT_LAYER);

        host_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        host_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        host_jLabel.setText("Host:");
        host_jLabel.setVerifyInputWhenFocusTarget(false);
        host_jLabel.setBounds(90, 80, 80, 15);
        configuracion_jLayeredPane.add(host_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        puerto_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        puerto_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        puerto_jLabel.setText("Puerto:");
        puerto_jLabel.setVerifyInputWhenFocusTarget(false);
        puerto_jLabel.setBounds(90, 110, 80, 15);
        configuracion_jLayeredPane.add(puerto_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        actualizar_configuracion_jButton.setText("Actualizar");
        actualizar_configuracion_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_configuracion_jButtonActionPerformed(evt);
            }
        });
        actualizar_configuracion_jButton.setBounds(169, 220, 120, 23);
        configuracion_jLayeredPane.add(actualizar_configuracion_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        adaTabbedPane.addTab(" Configuración ", configuracion_jLayeredPane);

        modulo.setBounds(190, 80, 120, 20);
        conexion_jLayeredPane.add(modulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        conexion_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        conexion_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        conexion_jLabel.setText("Conexión:");
        conexion_jLabel.setVerifyInputWhenFocusTarget(false);
        conexion_jLabel.setBounds(90, 30, 80, 15);
        conexion_jLayeredPane.add(conexion_jLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        base_datos.setBounds(190, 110, 120, 20);
        conexion_jLayeredPane.add(base_datos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Base de Datos:");
        jLabel6.setVerifyInputWhenFocusTarget(false);
        jLabel6.setBounds(50, 110, 120, 15);
        conexion_jLayeredPane.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        clave_bd.setBounds(190, 170, 120, 20);
        conexion_jLayeredPane.add(clave_bd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        usuario_bd.setBounds(190, 140, 120, 20);
        conexion_jLayeredPane.add(usuario_bd, javax.swing.JLayeredPane.DEFAULT_LAYER);

        conexion_jComboBox.setBounds(190, 30, 190, 20);
        conexion_jLayeredPane.add(conexion_jComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Usuario:");
        jLabel7.setVerifyInputWhenFocusTarget(false);
        jLabel7.setBounds(40, 140, 130, 15);
        conexion_jLayeredPane.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Clave:");
        jLabel8.setVerifyInputWhenFocusTarget(false);
        jLabel8.setBounds(40, 170, 130, 15);
        conexion_jLayeredPane.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Módulo:");
        jLabel9.setVerifyInputWhenFocusTarget(false);
        jLabel9.setBounds(40, 80, 130, 15);
        conexion_jLayeredPane.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ingresar_conexion_jButton.setText("Ingresar");
        ingresar_conexion_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_conexion_jButtonActionPerformed(evt);
            }
        });
        ingresar_conexion_jButton.setBounds(43, 220, 100, 23);
        conexion_jLayeredPane.add(ingresar_conexion_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        actualizar_conexion_jButton.setText("Actualizar");
        actualizar_conexion_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_conexion_jButtonActionPerformed(evt);
            }
        });
        actualizar_conexion_jButton.setBounds(169, 220, 120, 23);
        conexion_jLayeredPane.add(actualizar_conexion_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        eliminar_conexion_jButton.setText("Eliminar");
        eliminar_conexion_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_conexion_jButtonActionPerformed(evt);
            }
        });
        eliminar_conexion_jButton.setBounds(310, 220, 100, 23);
        conexion_jLayeredPane.add(eliminar_conexion_jButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        adaTabbedPane.addTab(" Conexión ", conexion_jLayeredPane);

        actualizar_conexion_jButton1.setText("Salir");
        actualizar_conexion_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_conexion_jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplicación para Acceso a Datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                            .addComponent(adaTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(actualizar_conexion_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adaTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actualizar_conexion_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizar_conexion_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_conexion_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_actualizar_conexion_jButton1ActionPerformed

    private void eliminar_conexion_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_conexion_jButtonActionPerformed
        if (modulo.getText().compareTo("") != 0 && base_datos.getText().compareTo("") != 0 && usuario_bd.getText().compareTo("") != 0)
            if (id_conexion != null) {
                JOptionPane.showMessageDialog(this, conexion.eliminar_conexion(id_conexion.toString()));
                cargar_conexiones();
            } else
                JOptionPane.showMessageDialog(this, "No ha seleccionado dato a eliminar.");
        else
            JOptionPane.showMessageDialog(this, "No ha seleccionado dato a eliminar.");
}//GEN-LAST:event_eliminar_conexion_jButtonActionPerformed

    private void actualizar_conexion_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_conexion_jButtonActionPerformed
        if (modulo.getText().compareTo("") != 0 && base_datos.getText().compareTo("") != 0 && usuario_bd.getText().compareTo("") != 0)
            if (id_conexion != null) {
                JOptionPane.showMessageDialog(this, conexion.actualizar_conexion(id_conexion.toString(), modulo.getText(), base_datos.getText(), usuario_bd.getText(), clave_bd.getText()));
                cargar_conexiones();
            } else
                JOptionPane.showMessageDialog(this, "No ha seleccionado dato a actualizar.");
        else
            JOptionPane.showMessageDialog(this, "Todos los campos son necesarios.");
}//GEN-LAST:event_actualizar_conexion_jButtonActionPerformed

    private void ingresar_conexion_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_conexion_jButtonActionPerformed
        if (modulo.getText().compareTo("") != 0 && base_datos.getText().compareTo("") != 0 && usuario_bd.getText().compareTo("") != 0) {
            JOptionPane.showMessageDialog(this, conexion.ingresar_conexion(modulo.getText(), base_datos.getText(), usuario_bd.getText(), clave_bd.getText()));
            cargar_conexiones();
        } else
            JOptionPane.showMessageDialog(this, "Todos los campos son necesarios.");
}//GEN-LAST:event_ingresar_conexion_jButtonActionPerformed

    private void actualizar_configuracion_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_configuracion_jButtonActionPerformed
        JOptionPane.showMessageDialog(this, this.conexion.actualizar_configuracion(this.host.getText(), this.puerto.getText()));
}//GEN-LAST:event_actualizar_configuracion_jButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AD_Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar_conexion_jButton;
    private javax.swing.JButton actualizar_conexion_jButton1;
    private javax.swing.JButton actualizar_configuracion_jButton;
    private javax.swing.JTabbedPane adaTabbedPane;
    private javax.swing.JTextField base_datos;
    private javax.swing.JTextField clave_bd;
    private javax.swing.JComboBox conexion_jComboBox;
    private javax.swing.JLabel conexion_jLabel;
    private javax.swing.JLayeredPane conexion_jLayeredPane;
    private javax.swing.JLayeredPane configuracion_jLayeredPane;
    private javax.swing.JButton eliminar_conexion_jButton;
    private javax.swing.JTextField host;
    private javax.swing.JLabel host_jLabel;
    private javax.swing.JButton ingresar_conexion_jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField modulo;
    private javax.swing.JTextField puerto;
    private javax.swing.JLabel puerto_jLabel;
    private javax.swing.JTextField usuario_bd;
    // End of variables declaration//GEN-END:variables

}
