// 
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : GI_Grupo_Investigacion.java
//  @ Date : 23/04/2009
//  @ Author : Guillermo Pizarro
//
//

package websae.mgi.dominio;

import java.math.BigDecimal;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import mad.eventos.Datos;
import mad.objetos.Registro;
import mad.objetos.Table;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import websae.informacion.Estado;
import websae.mae.dominio.AE_Organizador;

public class GI_Grupo_Investigacion {

    // <editor-fold defaultstate="collapsed" desc="Objetos Dependientes">
	public List< AE_Organizador > ref_organizador;
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Atributos">
	private BigDecimal gi_id_grupo_investigacion;
	private String gi_nombre;
	private String gi_objetivo;
	private String gi_logo;
	private String gi_web;
	private String gi_telefono;
    // </editor-fold>
    
    public GI_Grupo_Investigacion() {
    }
    
    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    
    public BigDecimal getGi_id_grupo_investigacion() {
        return gi_id_grupo_investigacion;
    }

    public void setGi_id_grupo_investigacion(BigDecimal gi_id_grupo_investigacion) {
        this.gi_id_grupo_investigacion = gi_id_grupo_investigacion;
    }

    public String getGi_logo() {
        return gi_logo;
    }

    public void setGi_logo(String gi_logo) {
        this.gi_logo = gi_logo;
    }

    public String getGi_nombre() {
        return gi_nombre;
    }

    public void setGi_nombre(String gi_nombre) {
        this.gi_nombre = gi_nombre;
    }

    public String getGi_objetivo() {
        return gi_objetivo;
    }

    public void setGi_objetivo(String gi_objetivo) {
        this.gi_objetivo = gi_objetivo;
    }

    public String getGi_telefono() {
        return gi_telefono;
    }

    public void setGi_telefono(String gi_telefono) {
        this.gi_telefono = gi_telefono;
    }

    public String getGi_web() {
        return gi_web;
    }

    public void setGi_web(String gi_web) {
        this.gi_web = gi_web;
    }

    public List<AE_Organizador> getRef_organizador() {
        return ref_organizador;
    }

    public void setRef_organizador(List<AE_Organizador> ref_organizador) {
        this.ref_organizador = ref_organizador;
    }
    // </editor-fold>

	public void cr_GI_Grupo_Investigacion(Table objeto) {
        this.gi_id_grupo_investigacion = new BigDecimal( (Long) objeto.get("gi_id_grupo_investigacion") );
        this.gi_nombre = (String) objeto.get("gi_nombre");
        this.gi_objetivo = (String) objeto.get("gi_objetivo");
        this.gi_logo = (String) objeto.get("gi_logo");
        this.gi_web = (String) objeto.get("gi_web");
        this.gi_telefono = (String) objeto.get("gi_telefono");
	}
	
	public void fin_GI_Grupo_Investigacion() {
	}

    public static GI_Grupo_Investigacion buscar_grupo_investigacion(BigDecimal id_grupo_investigacion) {
        GI_Grupo_Investigacion elemento = new GI_Grupo_Investigacion();

        Datos dato = new Datos("WebSAE");
        String sql = "SELECT * FROM gi_grupo_investigacion WHERE gi_id_grupo_investigacion = " + id_grupo_investigacion.toString() + ";";
        Registro registros = dato.consulta( sql );
        for (int i=0; i<registros.size(); i++) {
            Table objeto = registros.get(i);
            elemento.cr_GI_Grupo_Investigacion( objeto );
        }
        return elemento;
    }

    public static List< GI_Grupo_Investigacion > mostrar_grupos_investigacion_evento(String id_evento) {
        List< GI_Grupo_Investigacion > elementos = new LinkedList< GI_Grupo_Investigacion >();

        Datos dato = new Datos("WebSAE");
        String sql = "SELECT * FROM gi_grupo_investigacion WHERE gi_id_grupo_investigacion IN (SELECT ref_grupo_investigacion FROM ae_organizador WHERE ref_evento=" + id_evento + ");";
        Registro registros = dato.consulta( sql );
        for (int i=0; i<registros.size(); i++) {
            Table objeto = registros.get(i);
            GI_Grupo_Investigacion elemento = new GI_Grupo_Investigacion();
            elemento.cr_GI_Grupo_Investigacion( objeto );
            elementos.add( elemento );
        }
        return elementos;
    }

    public static List< GI_Grupo_Investigacion > mostrar_grupos_investigacion(String modulo) {
        List< GI_Grupo_Investigacion > elementos = new LinkedList< GI_Grupo_Investigacion >();
        
        Datos dato = new Datos( modulo );
        String sql = "SELECT * FROM gi_grupo_investigacion WHERE gi_estado = '" + Estado.VIGENTE + "';";
        Registro registros = dato.consulta( sql );
        for (int i=0; i<registros.size(); i++) {
            Table objeto = registros.get(i);
            GI_Grupo_Investigacion elemento = new GI_Grupo_Investigacion();
            elemento.cr_GI_Grupo_Investigacion( objeto );
            elementos.add( elemento );
        }
        return elementos;
    }
    
    public static List< GI_Grupo_Investigacion > grupos_investigacion() {
        List< GI_Grupo_Investigacion > elementos = new LinkedList< GI_Grupo_Investigacion >();

        Datos dato = new Datos("WebSAE");
        String sql = "SELECT * FROM gi_grupo_investigacion;";
        Registro registros = dato.consulta( sql );
        for (int i=0; i<registros.size(); i++) {
            Table objeto = registros.get(i);
            GI_Grupo_Investigacion elemento = new GI_Grupo_Investigacion();
            elemento.cr_GI_Grupo_Investigacion( objeto );
            elementos.add( elemento );
        }
        return elementos;
    }

    public static JSONObject toJSON(List< GI_Grupo_Investigacion > elementos) {
        JSONObject json = new JSONObject();
        try {
            JSONArray jsonItems = new JSONArray();
            for (Iterator< GI_Grupo_Investigacion > it = elementos.iterator(); it.hasNext();) {
                GI_Grupo_Investigacion elemento = it.next();
                jsonItems.put( toJSONObject( elemento ) );
            }
            json.put("identifier", "id_grupo_investigacion");
            json.put("label", "nombre");
            json.put("items", jsonItems);
        } catch (JSONException ex) {
            Logger.getLogger(GI_Grupo_Investigacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }

    public static JSONObject toJSONObject(GI_Grupo_Investigacion elemento) {
        JSONObject json = new JSONObject();
        try {
            json.put("id_grupo_investigacion", elemento.getGi_id_grupo_investigacion() );
            json.put("nombre", elemento.getGi_nombre() );
            json.put("objetivo", elemento.getGi_objetivo() );
            json.put("logo", elemento.getGi_logo() );
            json.put("web", elemento.getGi_web() );
            json.put("telefono", elemento.getGi_telefono() );
        } catch (Exception ex) {
            Logger.getLogger(GI_Grupo_Investigacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }
}
