//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : AE_Conferencista_Evento.java
//  @ Date : 23/04/2009
//  @ Author : Guillermo Pizarro
//
//
package websae.mae.dominio;

import java.math.BigDecimal;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import mad.eventos.Datos;
import mad.objetos.Registro;
import mad.objetos.Table;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import websae.mac.dominio.AC_Usuario;
import websae.mac.dominio.AC_Usuario_Perfil;

public class AE_Conferencista_Evento {

    // <editor-fold defaultstate="collapsed" desc="Objetos Maestros">
    public AE_Evento ref_evento;
    public AC_Usuario_Perfil ref_usuario_perfil;
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Objetos Dependientes">
    public List<AE_Conferencista_Evento_Articulo> ref_conferencista_evento_articulo;
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Atributos">
    private BigDecimal ce_id_conferencista_evento;
    private Boolean ce_invitado;
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Atributos de información">
    public static int CONFERENCISTA = 0;
    public static int CONFERENCISTA_INVITADO = 1;
    public static int CONFERENCISTA_EXPOSITOR = 2;
    // </editor-fold>
    
    public AE_Conferencista_Evento() {
        this.ref_usuario_perfil = new AC_Usuario_Perfil();
    }

    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public BigDecimal getCe_id_conferencista_evento() {
        return ce_id_conferencista_evento;
    }

    public void setCe_id_conferencista_evento(BigDecimal ce_id_conferencista_evento) {
        this.ce_id_conferencista_evento = ce_id_conferencista_evento;
    }

    public Boolean getCe_invitado() {
        return ce_invitado;
    }

    public void setCe_invitado(Boolean ce_invitado) {
        this.ce_invitado = ce_invitado;
    }

    public List<AE_Conferencista_Evento_Articulo> getRef_conferencista_evento_articulo() {
        return ref_conferencista_evento_articulo;
    }

    public void setRef_conferencista_evento_articulo(List<AE_Conferencista_Evento_Articulo> ref_conferencista_evento_articulo) {
        this.ref_conferencista_evento_articulo = ref_conferencista_evento_articulo;
    }

    public AE_Evento getRef_evento() {
        return ref_evento;
    }

    public void setRef_evento(AE_Evento ref_evento) {
        this.ref_evento = ref_evento;
    }

    public AC_Usuario_Perfil getRef_usuario_perfil() {
        return ref_usuario_perfil;
    }

    public void setRef_usuario_perfil(AC_Usuario_Perfil ref_usuario_perfil) {
        this.ref_usuario_perfil = ref_usuario_perfil;
    }
    // </editor-fold>

    public void cr_AE_Conferencista_Evento(Table objeto) {
        this.ce_id_conferencista_evento = new BigDecimal((Long) objeto.get("ce_id_conferencista_evento"));
        this.ce_invitado = (Boolean) objeto.get("ce_invitado");
        this.ref_usuario_perfil.setUp_id_usuario_perfil(new BigDecimal((Long) objeto.get("ref_usuario_perfil")));
    }

    public void fin_AE_Conferencista_Evento() {
    }
    
    public static List<AE_Conferencista_Evento> conferencistas_evento(String id_evento, int tipo_conferencista) {
        List<AE_Conferencista_Evento> elementos = new LinkedList<AE_Conferencista_Evento>();

        Datos dato = new Datos("WebSAE");
        String sql = "";
        if (tipo_conferencista == CONFERENCISTA) {
            sql = "SELECT * FROM ae_conferencista_Evento WHERE ref_evento = " + id_evento + ";";
        } else if (tipo_conferencista == CONFERENCISTA_EXPOSITOR) {
            sql = "SELECT * FROM ae_conferencista_Evento WHERE ref_evento = " + id_evento + " AND ce_invitado = 1;";
        } else if (tipo_conferencista == CONFERENCISTA_INVITADO) {
            sql = "SELECT * FROM ae_conferencista_Evento WHERE ref_evento = " + id_evento + " AND ce_invitado = 0;";
        }
        Registro registros = dato.consulta(sql);
        for (int i = 0; i < registros.size(); i++) {
            Table objeto = registros.get(i);
            AE_Conferencista_Evento elemento = new AE_Conferencista_Evento();
            elemento.cr_AE_Conferencista_Evento(objeto);
            elementos.add(elemento);
        }
        return elementos;
    }

    public static JSONObject toJSON(List<AE_Conferencista_Evento> elementos) {
        JSONObject json = new JSONObject();
        try {
            JSONArray jsonItems = new JSONArray();
            for (Iterator<AE_Conferencista_Evento> it = elementos.iterator(); it.hasNext();) {
                AE_Conferencista_Evento elemento = it.next();
                jsonItems.put(toJSONObject(elemento));
            }
            json.put("identifier", "id_conferencista_evento");
            json.put("label", "id_conferencista_evento");
            json.put("items", jsonItems);
        } catch (JSONException ex) {
            Logger.getLogger(AE_Conferencista_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }

    public static JSONObject toJSONObject(AE_Conferencista_Evento elemento) {
        JSONObject json = new JSONObject();
        try {
            json.put("id_conferencista_evento", elemento.getCe_id_conferencista_evento());
            json.put("invitado", elemento.getCe_invitado());

            if (elemento.ref_usuario_perfil.getUp_id_usuario_perfil() != null) {
                AC_Usuario usuario = AC_Usuario_Perfil.buscar_usuario_perfil(elemento.ref_usuario_perfil.getUp_id_usuario_perfil().toString()).ref_usuario;
                json.put("usuario", AC_Usuario.toJSONObject(AC_Usuario.buscar_usuario(usuario.getUs_id_usuario().toString())));
            }
        } catch (Exception ex) {
            Logger.getLogger(AE_Conferencista_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }
}
