//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : AE_Conferencista_Evento_Articulo.java
//  @ Date : 23/04/2009
//  @ Author : Guillermo Pizarro
//
//
package websae.mae.dominio;

import java.math.BigDecimal;
import websae.mce.dominio.CE_Articulo;

public class AE_Conferencista_Evento_Articulo {

    // <editor-fold defaultstate="collapsed" desc="Objetos maestros">
    public AE_Conferencista_Evento ref_conferencista_evento;
    public CE_Articulo ref_articulo;
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Atributos">
    private BigDecimal ce_id_conferencista_evento_articulo;
    private String ce_estado;
    // </editor-fold>

    public AE_Conferencista_Evento_Articulo() {
    }

    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public String getCe_estado() {
        return ce_estado;
    }

    public void setCe_estado(String ce_estado) {
        this.ce_estado = ce_estado;
    }

    public BigDecimal getCe_id_conferencista_evento_articulo() {
        return ce_id_conferencista_evento_articulo;
    }

    public void setCe_id_conferencista_evento_articulo(BigDecimal ce_id_conferencista_evento_articulo) {
        this.ce_id_conferencista_evento_articulo = ce_id_conferencista_evento_articulo;
    }

    public CE_Articulo getRef_articulo() {
        return ref_articulo;
    }

    public void setRef_articulo(CE_Articulo ref_articulo) {
        this.ref_articulo = ref_articulo;
    }

    public AE_Conferencista_Evento getRef_conferencista_evento() {
        return ref_conferencista_evento;
    }

    public void setRef_conferencista_evento(AE_Conferencista_Evento ref_conferencista_evento) {
        this.ref_conferencista_evento = ref_conferencista_evento;
    }
    // </editor-fold>
    
    public void cr_AE_Conferencista_Evento_Articulo() {
    }

    public void fin_AE_Conferencista_Evento_Articulo() {
    }
}
