//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : AE_Evento_Opcion.java
//  @ Date : 23/04/2009
//  @ Author : Guillermo Pizarro
//
//

package websae.mae.dominio;

import java.math.BigDecimal;
import websae.mac.dominio.AC_Opcion;

public class AE_Evento_Opcion {
    
	public AE_Evento ref_evento;
	public AC_Opcion ref_opcion;
    
	private BigDecimal eo_id_evento_opcion;
	private String eo_estado;
    
	public void cr_AE_Evento_Opcion() {
	}
	
	public void fin_AE_Evento_Opcion() {
	}
}
