//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : AE_Faq.java
//  @ Date : 23/04/2009
//  @ Author : Guillermo Pizarro
//
//

package websae.mae.dominio;

import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import mad.eventos.Datos;
import mad.objetos.Registro;
import mad.objetos.Table;
import org.json.JSONObject;

public class AE_Faq {

    // <editor-fold defaultstate="collapsed" desc="Objeto Maestro">
	public AE_Evento ref_evento;
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Atributos">
	private BigDecimal fa_id_faq;
	private String fa_texto;
    // </editor-fold>
    
    public AE_Faq() {
    }

    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public String getFa_texto() {
        return fa_texto;
    }

    public void setFa_texto(String fa_texto) {
        this.fa_texto = fa_texto;
    }

    public BigDecimal getFa_id_faq() {
        return fa_id_faq;
    }

    public void setFa_id_faq(BigDecimal fa_id_faq) {
        this.fa_id_faq = fa_id_faq;
    }

    public AE_Evento getRef_evento() {
        return ref_evento;
    }

    public void setRef_evento(AE_Evento ref_evento) {
        this.ref_evento = ref_evento;
    }
    // </editor-fold>

	public void cr_AE_Faq(Table objeto) {
        this.fa_id_faq = new BigDecimal( (Long) objeto.get("fa_id_faq") );
        this.fa_texto = (String) objeto.get("fa_texto");
	}
	
	public void fin_AE_Faq() {
	}

    public static AE_Faq buscar_faq(String id_evento) {
        AE_Faq faq = new AE_Faq();
        
        Datos datos = new Datos("WebSAE");
        Registro registros = datos.consulta("SELECT * FROM ae_evento ev, ae_faq fa WHERE fa.fa_id_faq = ev.ref_faq AND ev.ev_id_evento = "+id_evento+";");
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            faq.cr_AE_Faq(objeto);
        }
        return faq;
    }

    public static JSONObject toJSONObject(AE_Faq elemento) {
        JSONObject json = new JSONObject();
        try {
            json.put("id_faq", elemento.getFa_id_faq() );
            json.put("texto", elemento.getFa_texto() );
        } catch (Exception ex) {
            Logger.getLogger(AE_Faq.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }
}
