//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : AE_Fecha_Evento.java
//  @ Date : 23/04/2009
//  @ Author : Guillermo Pizarro
//
//

package websae.mae.dominio;

import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import mad.eventos.Datos;
import mad.objetos.Registro;
import mad.objetos.Table;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import websae.informacion.Funciones;

public class AE_Fecha_Evento {

    // <editor-fold defaultstate="collapsed" desc="Objetos Maestros">
    private AE_Evento ref_evento;
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Objetos Dependientes">
    private List< AE_Actividad > ref_actividad;
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Atributos">
	private BigDecimal fe_id_fecha_evento;
	private Date fe_fecha;
    // </editor-fold>

    public AE_Fecha_Evento() {
    }
    
    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public List<AE_Actividad> getRef_actividad() {
        return ref_actividad;
    }

    public void setRef_actividad(List<AE_Actividad> ref_actividad) {
        this.ref_actividad = ref_actividad;
    }

    public AE_Evento getRef_evento() {
        return ref_evento;
    }

    public void setRef_evento(AE_Evento ref_evento) {
        this.ref_evento = ref_evento;
    }

    public Date getFe_fecha() {
        return this.fe_fecha;
    }

    public void setFe_fecha(Date fe_fecha) {
        this.fe_fecha = fe_fecha;
    }

    public BigDecimal getFe_id_fecha_evento() {
        return fe_id_fecha_evento;
    }
    
    public void setFe_fecha(String fe_fecha) {
        if (fe_fecha != null) {
            DateFormat fecha = new SimpleDateFormat("yyyy-MM-dd");
            try {
                this.fe_fecha = (Date) fecha.parse(fe_fecha);
            } catch (ParseException ex) {
                this.fe_fecha = null;
                Logger.getLogger(AE_Fecha_Evento.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else
            this.fe_fecha = null;
    }

    public void setFe_id_fecha_evento(BigDecimal fe_id_fecha_evento) {
        this.fe_id_fecha_evento = fe_id_fecha_evento;
    }
    // </editor-fold>

	public void cr_AE_Fecha_Evento(Table objeto) {
        this.fe_id_fecha_evento = new  BigDecimal( (Long)  objeto.get("fe_id_fecha_evento") );
        this.fe_fecha = (Date) objeto.get("fe_fecha");
	}
	
	public void fin_AE_Fecha_Evento() {
	
	}

    public static List< AE_Fecha_Evento > buscar_fecha_evento(String id_evento) {
        List< AE_Fecha_Evento > fechas_evento = new LinkedList< AE_Fecha_Evento >();

        Datos datos = new Datos("WebSAE");
        String sql = "SELECT * FROM ae_evento ev, ae_fecha_evento fe " +
                     "WHERE ev.ev_id_evento = fe.ref_evento AND fe.ref_evento = "+id_evento+" " +
                     "ORDER BY fe.fe_fecha;";
        Registro registros = datos.consulta( sql );
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            AE_Fecha_Evento fecha_evento = new AE_Fecha_Evento();
            fecha_evento.cr_AE_Fecha_Evento(objeto);
            fechas_evento.add( fecha_evento );
        }
        return fechas_evento;
    }

    public static JSONObject toJSON(List< AE_Fecha_Evento > fechas_eventos, String id_evento) {
        JSONObject json = new JSONObject();
        try {
            JSONArray jsonItems = new JSONArray();
            for (Iterator<AE_Fecha_Evento> it = fechas_eventos.iterator(); it.hasNext();) {
                AE_Fecha_Evento fecha_evento = it.next();
                jsonItems.put( toJSONObject( fecha_evento, id_evento ) );
            }
            json.put("identifier", "id_fecha_evento");
            json.put("label", "fecha");
            json.put("items", jsonItems);
        } catch (JSONException ex) {
            Logger.getLogger(AE_Fecha_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }
    
    public static JSONObject toJSONObject(AE_Fecha_Evento fecha_evento, String id_evento) {
        JSONObject json = new JSONObject();
        try {
            json.put("id_fecha_evento", fecha_evento.getFe_id_fecha_evento() );
            json.put("fecha", fecha_evento.getFe_fecha() );
            json.put("fecha_long", Funciones.fecha_formato_agenda(fecha_evento.getFe_fecha().toString()) );
        } catch (Exception ex) {
            Logger.getLogger(AE_Fecha_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }
}
