//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : AE_Material_Registro.java
//  @ Date : 23/04/2009
//  @ Author : Guillermo Pizarro
//
//

package websae.mae.dominio;

import java.math.BigDecimal;

public class AE_Material_Registro {
    
    // <editor-fold defaultstate="collapsed" desc="Objetos Maestros">
	public AE_Material ref_material;
	public AE_Registro ref_registro;
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Atributos">
    private BigDecimal mr_id_material_registro;
	private Integer mr_cantidad_adicional;
	private String mr_estado;
    // </editor-fold>
    
    public AE_Material_Registro() {
    }
    
    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public Integer getMr_cantidad_adicional() {
        return mr_cantidad_adicional;
    }

    public void setMr_cantidad_adicional(Integer mr_cantidad_adicional) {
        this.mr_cantidad_adicional = mr_cantidad_adicional;
    }

    public String getMr_estado() {
        return mr_estado;
    }

    public void setMr_estado(String mr_estado) {
        this.mr_estado = mr_estado;
    }

    public BigDecimal getMr_id_material_registro() {
        return mr_id_material_registro;
    }

    public void setMr_id_material_registro(BigDecimal mr_id_material_registro) {
        this.mr_id_material_registro = mr_id_material_registro;
    }

    public AE_Material getRef_material() {
        return ref_material;
    }

    public void setRef_material(AE_Material ref_material) {
        this.ref_material = ref_material;
    }

    public AE_Registro getRef_registro() {
        return ref_registro;
    }

    public void setRef_registro(AE_Registro ref_registro) {
        this.ref_registro = ref_registro;
    }
    // </editor-fold>
    
    public void cr_AE_Material_Registro() {
	}
	
	public void fin_AE_Material_Registro() {
	}
}
