//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : AE_Subcategoria_Evento.java
//  @ Date : 23/04/2009
//  @ Author : Guillermo Pizarro
//
//

package websae.mae.dominio;

import java.math.BigDecimal;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import mad.eventos.Datos;
import mad.objetos.Registro;
import mad.objetos.Table;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

public class AE_Subcategoria_Evento {
    
    // <editor-fold defaultstate="collapsed" desc="Objetos Maestros">
	public AE_Subcategoria ref_subcategoria;
	public AE_Evento ref_evento;
    // </editor-fold>
    
	// <editor-fold defaultstate="collapsed" desc="Objetos Dependientes">
    public List< AE_Registro > ref_registro;
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Atributos">
	private BigDecimal se_id_subcategoria_evento;
	private Float se_porcentaje_descuento;
    // </editor-fold>
    
    public AE_Subcategoria_Evento() {
        this.ref_subcategoria = new AE_Subcategoria();
    }
    
    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public AE_Evento getRef_evento() {
        return ref_evento;
    }

    public void setRef_evento(AE_Evento ref_evento) {
        this.ref_evento = ref_evento;
    }

    public List<AE_Registro> getRef_registro() {
        return ref_registro;
    }

    public void setRef_registro(List<AE_Registro> ref_registro) {
        this.ref_registro = ref_registro;
    }

    public AE_Subcategoria getRef_subcategoria() {
        return ref_subcategoria;
    }

    public void setRef_subcategoria(AE_Subcategoria ref_subcategoria) {
        this.ref_subcategoria = ref_subcategoria;
    }

    public BigDecimal getSe_id_subcategoria_evento() {
        return se_id_subcategoria_evento;
    }

    public void setSe_id_subcategoria_evento(BigDecimal se_id_subcategoria_evento) {
        this.se_id_subcategoria_evento = se_id_subcategoria_evento;
    }

    public Float getSe_porcentaje_descuento() {
        return se_porcentaje_descuento;
    }

    public void setSe_porcentaje_descuento(Float se_porcentaje_descuento) {
        this.se_porcentaje_descuento = se_porcentaje_descuento;
    }
    // </editor-fold>
    
	public void cr_AE_Subcategoria_Evento(Table objeto) {
        this.se_id_subcategoria_evento = new BigDecimal( (Long) objeto.get("se_id_subcategoria_evento") );
        this.se_porcentaje_descuento = (Float) objeto.get("se_porcentaje_descuento");
        this.ref_subcategoria.setSu_id_subcategoria( new BigDecimal( (Long) objeto.get("ref_subcategoria") ) );
	}
	
	public void fin_AE_Subcategoria_Evento() {
	}

    public static AE_Subcategoria_Evento buscar_subcategoria_evento(BigDecimal id_subcategoria_evento) {
        AE_Subcategoria_Evento elemento = new AE_Subcategoria_Evento();
        
        Datos datos = new Datos("WebSAE");
        String sql = "SELECT * FROM ae_subcategoria_Evento WHERE se_id_subcategoria_evento = "+id_subcategoria_evento+";";
        Registro registros = datos.consulta( sql );
        for (int i=0; i<registros.size(); i++)
            elemento.cr_AE_Subcategoria_Evento( (Table) registros.get(i) );
        
        return elemento;
    }

    public static List< AE_Subcategoria_Evento > mostrar_subcategorias_evento(String id_categoria, String id_evento) {
        List< AE_Subcategoria_Evento > elementos = new LinkedList< AE_Subcategoria_Evento >();
        
        Datos datos = new Datos("WebSAE");
        String sql = "SELECT * FROM ae_subcategoria_Evento se, AE_Subcategoria su WHERE se.ref_subcategoria = su.su_id_subcategoria AND su.ref_categoria = "+id_categoria+" AND se.ref_evento = "+id_evento+";";
        Registro registros = datos.consulta( sql );
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            AE_Subcategoria_Evento elemento = new AE_Subcategoria_Evento();
            elemento.cr_AE_Subcategoria_Evento( objeto );
            elementos.add( elemento );
        }
        return elementos;
    }
    
    public static JSONObject toJSON(List< AE_Subcategoria_Evento > auspicios) {
        JSONObject json = new JSONObject();
        try {
            JSONArray jsonItems = new JSONArray();
            for (Iterator< AE_Subcategoria_Evento > it = auspicios.iterator(); it.hasNext();) {
                AE_Subcategoria_Evento elemento = it.next();
                jsonItems.put( toJSONObject( elemento ) );
            }
            json.put("identifier", "id_subcategoria_evento");
            json.put("label", "porcentaje_descuento");
            json.put("items", jsonItems);
        } catch (JSONException ex) {
            Logger.getLogger(AE_Subcategoria_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }
    
    public static JSONObject toJSONObject(AE_Subcategoria_Evento elemento) {
        JSONObject json = new JSONObject();
        try {
            json.put("id_subcategoria_evento", elemento.getSe_id_subcategoria_evento() );
            json.put("porcentaje_descuento", elemento.getSe_porcentaje_descuento() );

            if (elemento.ref_subcategoria.getSu_id_subcategoria() != null)
                json.put("subcategoria", AE_Subcategoria.toJSONObject( AE_Subcategoria.buscar_subcategoria( elemento.ref_subcategoria.getSu_id_subcategoria().toString() ) ) );
        } catch (Exception ex) {
            Logger.getLogger(AE_Subcategoria_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }    
}
