//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : AE_Tipo_Material.java
//  @ Date : 23/04/2009
//  @ Author : Guillermo Pizarro
//
//

package websae.mae.dominio;

import java.math.BigDecimal;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.LinkedBlockingDeque;
import java.util.logging.Level;
import java.util.logging.Logger;
import mad.eventos.Datos;
import mad.objetos.Registro;
import mad.objetos.Table;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

public class AE_Tipo_Material {

    // <editor-fold defaultstate="collapsed" desc="Objetos Dependientes">
	public List< AE_Material > ref_material;
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Atributos">
	private BigDecimal tm_id_tipo_material;
	private String tm_nombre;
	private String tm_estado;
    // </editor-fold>

    public AE_Tipo_Material() {
    }
    
    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public List<AE_Material> getRef_material() {
        return ref_material;
    }

    public void setRef_material(List<AE_Material> ref_material) {
        this.ref_material = ref_material;
    }

    public String getTm_estado() {
        return tm_estado;
    }

    public void setTm_estado(String tm_estado) {
        this.tm_estado = tm_estado;
    }

    public BigDecimal getTm_id_tipo_material() {
        return tm_id_tipo_material;
    }

    public void setTm_id_tipo_material(BigDecimal tm_id_tipo_material) {
        this.tm_id_tipo_material = tm_id_tipo_material;
    }

    public String getTm_nombre() {
        return tm_nombre;
    }

    public void setTm_nombre(String tm_nombre) {
        this.tm_nombre = tm_nombre;
    }
    // </editor-fold>
    
	public void cr_AE_Tipo_Material(Table objeto) {
        this.tm_id_tipo_material = new BigDecimal( (Long) objeto.get("tm_id_tipo_material") );
        this.tm_nombre = (String) objeto.get("tm_nombre");
        this.tm_estado = (String) objeto.get("tm_estado");
	}
	
	public void fin_AE_Tipo_Material() {
	
	}

    public static AE_Tipo_Material buscar_tipo_material(String id_tipo_material) {
        AE_Tipo_Material elemento = new AE_Tipo_Material();

        Datos datos = new Datos("WebSAE");
        Registro registros = datos.consulta("SELECT * FROM ae_tipo_material WHERE tm_id_tipo_material = "+id_tipo_material+";");
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            elemento.cr_AE_Tipo_Material(objeto);
        }
        return elemento;
    }
    
    public static List< AE_Tipo_Material > tipos_materiales( ) {
        List< AE_Tipo_Material > tipos_materiales = new LinkedList<AE_Tipo_Material>();
        
        Datos datos = new Datos("WebSAE");
        Registro registros = datos.consulta("SELECT * FROM ae_tipo_material ORDER BY tm_nombre;");
        for (int i=0; i<registros.size(); i++) {
            Table objeto = (Table) registros.get(i);
            AE_Tipo_Material elemento = new AE_Tipo_Material();
            elemento.cr_AE_Tipo_Material(objeto);
            tipos_materiales.add(elemento);
        }
        return tipos_materiales;
    }

    public static JSONObject toJSON(List< AE_Tipo_Material > tipos_material) {
        JSONObject json = new JSONObject();
        try {
            JSONArray jsonItems = new JSONArray();
            for (Iterator<AE_Tipo_Material> it = tipos_material.iterator(); it.hasNext();) {
                AE_Tipo_Material elemento = it.next();
                jsonItems.put( toJSONObject( elemento ) );
            }
            json.put("identifier", "id_tipo_material");
            json.put("label", "nombre");
            json.put("items", jsonItems);
        } catch (JSONException ex) {
            Logger.getLogger(AE_Tipo_Material.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }

    public static JSONObject toJSONObject(AE_Tipo_Material elemento) {
        JSONObject json = new JSONObject();
        try {
            json.put("id_tipo_material", elemento.getTm_id_tipo_material() );
            json.put("nombre", elemento.getTm_nombre() );
            json.put("estado", elemento.getTm_estado() );
        } catch (Exception ex) {
            Logger.getLogger(AE_Tipo_Material.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }    
}
