//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : SU_Tipo_Empresa_Cargo.java
//  @ Date : 28/03/2009
//  @ Author : Guillermo Pizarro
//  @ Version : v1.0.0
//
//

package websae.msu.informacion;

import java.math.BigDecimal;
import websae.msu.dominio.SU_Cargo;
import websae.msu.dominio.SU_Tipo_Empresa;

public class SU_Tipo_Empresa_Cargo {

    // <editor-fold defaultstate="collapsed" desc="Objetos dependientes">
    public SU_Tipo_Empresa ref_tipo_empresa;
	public SU_Cargo ref_cargo;
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Atributos">
	private BigDecimal te_id_tipo_empresa_cargo;
	private String te_estado;
    // </editor-fold>

    public SU_Tipo_Empresa_Cargo() {
        this.ref_cargo = new SU_Cargo();
        this.ref_tipo_empresa = new SU_Tipo_Empresa();
    }

    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public String getTe_estado() {
        return te_estado;
    }

    public void setTe_estado(String te_estado) {
        this.te_estado = te_estado;
    }

    public BigDecimal getTe_id_tipo_empresa_cargo() {
        return te_id_tipo_empresa_cargo;
    }

    public void setTe_id_tipo_empresa_cargo(BigDecimal te_id_tipo_empresa_cargo) {
        this.te_id_tipo_empresa_cargo = te_id_tipo_empresa_cargo;
    }

    public SU_Cargo getRef_cargo() {
        return ref_cargo;
    }

    public SU_Tipo_Empresa getRef_tipo_empresa() {
        return ref_tipo_empresa;
    }
    // </editor-fold>
    
	public void cr_SU_Tipo_Empresa_Cargo() {
	
	}
	
	public void fin_SU_Tipo_Empresa_Cargo() {
	
	}
}
