//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE - Sistema de Administración de Eventos
//  @ File Name : AC_Perfil_Opcion.java
//  @ Date : 28/03/2009
//  @ Author : Guillermo Pizarro
//  @ Version : v1.0.0
//
//

package websae.mac.dominio;

import java.math.BigDecimal;

public class AC_Perfil_Opcion {
    
    // <editor-fold defaultstate="collapsed" desc="Objetos maestros">
	public AC_Perfil ref_perfil;
	public AC_Opcion ref_opcion;
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Atributos">
    private BigDecimal po_id_perfil_opcion;
    private String po_estado;
    // </editor-fold>
    
    public AC_Perfil_Opcion() {
        this.ref_opcion = new AC_Opcion();
        this.ref_perfil = new AC_Perfil();
    }

    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public String getPo_estado() {
        return po_estado;
    }

    public void setPo_estado(String po_estado) {
        this.po_estado = po_estado;
    }

    public BigDecimal getPo_id_perfil_opcion() {
        return po_id_perfil_opcion;
    }

    public void setPo_id_perfil_opcion(BigDecimal po_id_perfil_opcion) {
        this.po_id_perfil_opcion = po_id_perfil_opcion;
    }
    // </editor-fold>
    
	public void cr_AC_Perfil_Opcion() {
	}
	
	public void fin_AC_Perfil_Opcion() {
	}
}
