//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE - Sistema de Administración de Eventos
//  @ File Name : AC_Usuario_Perfil.java
//  @ Date : 28/03/2009
//  @ Author : Guillermo Pizarro
//  @ Version : v1.0.0
//
//
package websae.mac.dominio;

import java.math.BigDecimal;
import java.util.Iterator;
import java.util.List;
import mad.eventos.Datos;
import mad.eventos.Transaccion;
import mad.objetos.Registro;
import mad.objetos.Table;
import org.json.JSONArray;
import websae.informacion.Estado;
import websae.informacion.Funciones;

public class AC_Usuario_Perfil {

    // <editor-fold defaultstate="collapsed" desc="Objetos Maestros">
    public AC_Usuario ref_usuario;
    public AC_Perfil ref_perfil;
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Atributos">
    private BigDecimal up_id_usuario_perfil;
    private String up_estado;
    // </editor-fold>

    public AC_Usuario_Perfil() {
        this.ref_perfil = new AC_Perfil();
        this.ref_usuario = new AC_Usuario();
    }

    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public String getUp_estado() {
        return up_estado;
    }

    public void setUp_estado(String up_estado) {
        this.up_estado = up_estado;
    }

    public BigDecimal getUp_id_usuario_perfil() {
        return up_id_usuario_perfil;
    }

    public void setUp_id_usuario_perfil(BigDecimal up_id_usuario_perfil) {
        this.up_id_usuario_perfil = up_id_usuario_perfil;
    }
    // </editor-fold>

    public void cr_AC_Usuario_Perfil(Table objeto) {
        this.up_id_usuario_perfil = new BigDecimal((Long) objeto.get("up_id_usuario_perfil"));
        this.up_estado = (String) objeto.get("up_estado");
        this.ref_usuario.setUs_id_usuario(new BigDecimal((Long) objeto.get("ref_usuario")));
        this.ref_perfil.setPe_id_perfil(new BigDecimal((Long) objeto.get("ref_perfil")));
    }

    public static AC_Usuario buscar_usuario(BigDecimal id_usuario_perfil) {
        AC_Usuario elemento = new AC_Usuario();
        
        Datos dato = new Datos("WebSAE");
        String sql = "SELECT * FROM v_usuario us, ac_usuario_perfil up WHERE up.ref_usuario = us.us_id_usuario AND up.up_id_usuario_perfil = " + id_usuario_perfil + ";";
        Registro registros = dato.consulta(sql);
        for (int i = 0; i < registros.size(); i++)
            elemento.cr_AC_Usuario( registros.get(i) );
        
        return elemento;
    }
    
    public static AC_Usuario_Perfil buscar_usuario_perfil(String id_usuario_perfil) {
        AC_Usuario_Perfil elemento = new AC_Usuario_Perfil();
        
        Datos dato = new Datos("WebSAE");
        String sql = "SELECT * FROM ac_usuario_Perfil WHERE up_id_usuario_perfil = " + id_usuario_perfil + ";";
        Registro registros = dato.consulta(sql);
        for (int i = 0; i < registros.size(); i++) {
            Table objeto = registros.get(i);
            elemento.cr_AC_Usuario_Perfil(objeto);
        }
        return elemento;
    }
    
    public static AC_Usuario_Perfil buscar_usuario_perfil(BigDecimal id_usuario, BigDecimal id_perfil) {
        AC_Usuario_Perfil elemento = new AC_Usuario_Perfil();
        
        Datos dato = new Datos("WebSAE");
        String sql = "SELECT * FROM ac_usuario_perfil WHERE ref_usuario = " + id_usuario + " AND ref_perfil = " + id_perfil + ";";
        Registro registros = dato.consulta(sql);
        for (int i = 0; i < registros.size(); i++) {
            Table objeto = registros.get(i);
            elemento.cr_AC_Usuario_Perfil(objeto);
        }
        return elemento;
    }

    public static BigDecimal id_usuario_perfil(Transaccion transaccion, BigDecimal id_usuario, String id_perfil) {
        String sql = "SELECT up_id_usuario_perfil AS id FROM ac_usuario_perfil WHERE ref_usuario = " + id_usuario + " AND ref_perfil = " + id_perfil + " AND up_estado = '" + Estado.VIGENTE + "';";
        BigDecimal id = Funciones.obtener_id(transaccion, sql, "id");
        return id;
    }
    
    public static JSONArray toJSONPerfiles(List<AC_Usuario_Perfil> usuario_perfil) {
        JSONArray jsonItems = new JSONArray();
        for (Iterator<AC_Usuario_Perfil> it = usuario_perfil.iterator(); it.hasNext();) {
            jsonItems.put(AC_Perfil.toJSONObject((it.next()).ref_perfil));
        }
        return jsonItems;
    }
}
