//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : WebSAE
//  @ File Name : CE_Archivo.java
//  @ Date : 23/04/2009
//  @ Author : Guillermo Pizarro
//
//
package websae.mce.dominio;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import mad.eventos.Datos;
import mad.objetos.Registro;
import mad.objetos.Table;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import websae.informacion.Funciones;

public class CE_Archivo {
    
    // <editor-fold defaultstate="collapsed" desc="Objeto Maestro">
    public CE_Articulo ref_articulo;
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Atributos">
    private BigDecimal ar_id_archivo;
    private String ar_nombre;
    private Timestamp ar_fecha;
    // </editor-fold>
    
    public CE_Archivo() {
        this.ref_articulo = new CE_Articulo();
    }
    
    // <editor-fold defaultstate="collapsed" desc="Setters & Getters">
    public Timestamp getAr_fecha() {
        return ar_fecha;
    }

    public void setAr_fecha(Timestamp ar_fecha) {
        this.ar_fecha = ar_fecha;
    }

    public String getAr_nombre() {
        return ar_nombre;
    }

    public void setAr_nombre(String ar_nombre) {
        this.ar_nombre = ar_nombre;
    }

    public BigDecimal getAr_id_archivo() {
        return ar_id_archivo;
    }

    public void setAr_id_archivo(BigDecimal ar_id_archivo) {
        this.ar_id_archivo = ar_id_archivo;
    }

    public CE_Articulo getRef_articulo() {
        return ref_articulo;
    }

    public void setRef_articulo(CE_Articulo ref_articulo) {
        this.ref_articulo = ref_articulo;
    }
    // </editor-fold>
    
    public void cr_CE_Archivo(Table objeto) {
        this.ar_id_archivo = Funciones.getBigDecimal( objeto.get("ar_id_archivo") );
        this.ar_nombre = (String) objeto.get("ar_nombre");
        this.ar_fecha = (Timestamp) objeto.get("ar_fecha");
    }

    public static List< CE_Archivo > mostrar_archivos_por_articulo(BigDecimal id_articulo) {
        List< CE_Archivo > elementos = new LinkedList< CE_Archivo >();
        
        Datos datos = new Datos("WebSAE");
        String sql = "SELECT * FROM ce_archivo WHERE ref_articulo=" + id_articulo + " ORDER BY ar_fecha DESC;";
        Registro registros = datos.consulta(sql);
        for (int i = 0; i < registros.size(); i++) {
            CE_Archivo elemento = new CE_Archivo();
            elemento.cr_CE_Archivo( (Table) registros.get(i) );
            elementos.add( elemento );
        }
        return elementos;
    }
    
    public static CE_Archivo archivo_por_articulo(BigDecimal id_articulo) {
        CE_Archivo elemento = new CE_Archivo();

        Datos datos = new Datos("WebSAE");
        String sql = "SELECT * FROM ce_archivo c where ref_articulo = " + id_articulo + " ORDER BY ar_fecha DESC LIMIT 1;";
        Registro registros = datos.consulta(sql);
        for (int i = 0; i < registros.size(); i++)
            elemento.cr_CE_Archivo( (Table) registros.get(i) );
        
        return elemento;
    }

    public static JSONObject toJSON(List< CE_Archivo > elementos) {
        JSONObject json = new JSONObject();
        try {
            JSONArray jsonItems = new JSONArray();
            for (Iterator< CE_Archivo > it = elementos.iterator(); it.hasNext();)
                jsonItems.put( toJSONObject( it.next() ) );

            json.put("items", jsonItems);
        } catch (JSONException ex) {
            Logger.getLogger(CE_Archivo.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }

    public static JSONObject toJSONObject(CE_Archivo elemento) {
        JSONObject json = new JSONObject();
        try {
            json.put("id", elemento.getAr_id_archivo() );
            json.put("nombre", elemento.getAr_nombre() );
            json.put("fecha", elemento.getAr_fecha() );
        } catch (Exception ex) {
            Logger.getLogger(CE_Archivo.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }
}